/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Daily contribution data */
export interface DailyContribution {
  date: string
  totals: DailyTotals
  intensity: number
  tokenBreakdown: TokenBreakdown
  sources: Array<SourceContribution>
}

/** Daily contribution totals */
export interface DailyTotals {
  tokens: number
  cost: number
  messages: number
}

/** Data summary statistics */
export interface DataSummary {
  totalTokens: number
  totalCost: number
  totalDays: number
  activeDays: number
  averagePerDay: number
  maxCostInSingleDay: number
  sources: Array<string>
  models: Array<string>
}

/** Finalize graph with pricing */
export declare function finalizeGraph(options: FinalizeGraphOptions): GraphResult

/** Options for finalizing graph */
export interface FinalizeGraphOptions {
  homeDir?: string
  localMessages: ParsedMessages
  pricing: Array<PricingEntry>
  includeCursor: boolean
  since?: string
  until?: string
  year?: string
}

/** Options for finalizing monthly report */
export interface FinalizeMonthlyOptions {
  homeDir?: string
  localMessages: ParsedMessages
  pricing: Array<PricingEntry>
  includeCursor: boolean
  since?: string
  until?: string
  year?: string
}

/** Finalize monthly report with pricing */
export declare function finalizeMonthlyReport(options: FinalizeMonthlyOptions): MonthlyReport

/** Finalize model report: apply pricing to local messages, add Cursor, aggregate */
export declare function finalizeReport(options: FinalizeReportOptions): ModelReport

/** Options for finalizing report with pricing */
export interface FinalizeReportOptions {
  homeDir?: string
  localMessages: ParsedMessages
  pricing: Array<PricingEntry>
  includeCursor: boolean
  since?: string
  until?: string
  year?: string
}

/**
 * Generate graph data from all session sources
 *
 * This is the main entry point that orchestrates:
 * 1. Parallel file scanning
 * 2. Parallel session parsing
 * 3. Date filtering
 * 4. Parallel aggregation
 */
export declare function generateGraph(options: GraphOptions): GraphResult

/** Generate graph data with pricing calculation */
export declare function generateGraphWithPricing(options: ReportOptions): GraphResult

/** Get model usage report with pricing calculation */
export declare function getModelReport(options: ReportOptions): ModelReport

/** Get monthly usage report with pricing calculation */
export declare function getMonthlyReport(options: ReportOptions): MonthlyReport

/** Metadata about the graph generation */
export interface GraphMeta {
  generatedAt: string
  version: string
  dateRangeStart: string
  dateRangeEnd: string
  processingTimeMs: number
}

/** Configuration options for graph generation */
export interface GraphOptions {
  /** Home directory path (defaults to user's home) */
  homeDir?: string
  /** Sources to include: "opencode", "claude", "codex", "gemini" */
  sources?: Array<string>
  /** Start date filter (YYYY-MM-DD) */
  since?: string
  /** End date filter (YYYY-MM-DD) */
  until?: string
  /** Filter to specific year */
  year?: string
  /** Number of parallel threads (defaults to CPU count) */
  threads?: number
}

/** Complete graph result */
export interface GraphResult {
  meta: GraphMeta
  summary: DataSummary
  years: Array<YearSummary>
  contributions: Array<DailyContribution>
}

/** Simple health check to verify the native module is working */
export declare function healthCheck(): string

/** Options for parsing local sources only (no Cursor) */
export interface LocalParseOptions {
  homeDir?: string
  sources?: Array<string>
  since?: string
  until?: string
  year?: string
}

/** Pricing data for a single model (passed from TypeScript) */
export interface ModelPricing {
  inputCostPerToken: number
  outputCostPerToken: number
  cacheReadInputTokenCost?: number
  cacheCreationInputTokenCost?: number
}

/** Model report result */
export interface ModelReport {
  entries: Array<ModelUsage>
  totalInput: number
  totalOutput: number
  totalCacheRead: number
  totalCacheWrite: number
  totalMessages: number
  totalCost: number
  processingTimeMs: number
}

/** Model usage summary for reports */
export interface ModelUsage {
  source: string
  model: string
  provider: string
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reasoning: number
  messageCount: number
  cost: number
}

/** Monthly report result */
export interface MonthlyReport {
  entries: Array<MonthlyUsage>
  totalCost: number
  processingTimeMs: number
}

/** Monthly usage summary */
export interface MonthlyUsage {
  month: string
  models: Array<string>
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  messageCount: number
  cost: number
}

export interface ParsedMessage {
  source: string
  modelId: string
  providerId: string
  sessionId: string
  timestamp: number
  date: string
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reasoning: number
  agent?: string
}

/** Result of parsing local sources (excludes Cursor - it's network-synced) */
export interface ParsedMessages {
  messages: Array<ParsedMessage>
  opencodeCount: number
  claudeCount: number
  codexCount: number
  geminiCount: number
  processingTimeMs: number
}

/**
 * Parse local sources only (OpenCode, Claude, Codex, Gemini - NO Cursor)
 * This can run in parallel with network operations (Cursor sync, pricing fetch)
 */
export declare function parseLocalSources(options: LocalParseOptions): ParsedMessages

/** Entry in the pricing map */
export interface PricingEntry {
  modelId: string
  pricing: ModelPricing
}

/** Options for reports with pricing */
export interface ReportOptions {
  /** Home directory path (defaults to user's home) */
  homeDir?: string
  /** Sources to include: "opencode", "claude", "codex", "gemini" */
  sources?: Array<string>
  /** Pricing data for cost calculation */
  pricing: Array<PricingEntry>
  /** Start date filter (YYYY-MM-DD) */
  since?: string
  /** End date filter (YYYY-MM-DD) */
  until?: string
  /** Filter to specific year */
  year?: string
}

/** Scan for session files (for debugging/testing) */
export declare function scanSessions(homeDir?: string | undefined | null, sources?: Array<string> | undefined | null): ScanStats

/** Scan session files and return file counts per source */
export interface ScanStats {
  opencodeFiles: number
  claudeFiles: number
  codexFiles: number
  geminiFiles: number
  cursorFiles: number
  totalFiles: number
}

/** Source contribution for a specific day */
export interface SourceContribution {
  source: string
  modelId: string
  providerId: string
  tokens: TokenBreakdown
  cost: number
  messages: number
}

/** Token breakdown by type */
export interface TokenBreakdown {
  input: number
  output: number
  cacheRead: number
  cacheWrite: number
  reasoning: number
}

/** Version of the native module */
export declare function version(): string

/** Year summary */
export interface YearSummary {
  year: string
  totalTokens: number
  totalCost: number
  rangeStart: string
  rangeEnd: string
}
